### PR TITLE
Equatorial Crossing Time

### PR DESCRIPTION
**Pull request by sfinkens**
Add method to compute the equatorial crossing time of an orbit. 

A utility to read pygac-like TLE files (TLEs concatenated over time) can be added later.

 - [x] Tests added 
 - [x] Tests passed 
 - [x] Passes ``flake8 pyorbital`` 
 - [x] Fully documented

### CODE REVIEW

**Comment by sfinkens** [comment]
@mraspaud Of course! I'm also thinking about a switch to compute the crossing time of the descending node.

**Comment by adybbroe** [comment]
@sfinkens Should we add some tests and get this merged soon? I may be able to find some time to help out. As I am in closing/merging mode atm :-)

**Comment by sfinkens** [comment]
@adybbroe Instead of using the orbit number I tried to find the root of the cartesian z-coordinate (with constraint z-velocity > 0 for ascending node and < 0 for descending node). But I wasn't able to convince the optimization algorithm to converge...

**Comment by adybbroe** [comment]
Great, thanks @sfinkens This will be a useful feature. We will see if the orbit-number instability as I mentioned will become an issue

**Pull request merged**
