### PR TITLE
Added active.txt tle path to TLE_URLS

### LINKED ISSUE #52: Pyorbital fails to find TLE For some satellites
#### Code Sample, a minimal, complete, and verifiable piece of code

```python
from pyorbital.orbital import Orbital
sat_names = ['WORLDVIEW-1 (WV-1)', 'WORLDVIEW-2 (WV-2)', 'WORLDVIEW-3 (WV-3)',
             'SKYSAT-1', 'SKYSAT-2', 'SKYSAT-C1', 'SKYSAT-C2', 'SKYSAT-C3', 
             'SKYSAT-C4', 'SKYSAT-C5', 'SKYSAT-C6', 'SKYSAT-C7', 'SKYSAT-C8', 
             'SKYSAT-C9', 'SKYSAT-C10', 'SKYSAT-C11', 'SKYSAT-C12', 
             'SKYSAT-C13', 'GEOEYE 1', 'PATHFINDER 1', 'GLOBAL-1', 
             'BLACKSKY GLOBAL 2', 'GLOBAL-3', 'GLOBAL-4', 'PLEIADES 1A', 
             'PLEIADES 1B', 'DEIMOS-2', 'KOMPSAT-3A']

for sat in sat_names:
    orb = Orbital(sat)
    print (sat + ' Worked!')
```
#### Problem description

Pyorbital is having no problem finding the TLE for most of the satellites in the above list, but fails to find others. For example, it finds the TLE for all the SKYSAT-X satellites but fails for SKYSAT-C12 and SKYSAT-C13. I checked the names against the catalog in CelesTrak (https://celestrak.com/NORAD/elements/active.php) and verified the satellites are still in orbit 
(https://www.n2yo.com/database/?name=SKYSAT+C12#results)

It also fails for all of the GLOBAL satellites.

#### Expected Output
None
#### Actual Result, Traceback if applicable
KeyError: "Found no TLE entry for 'GLOBAL-4'"
#### Versions of Python, package at hand and relevant dependencies
Using Python 3.6

### PR DESCRIPTION
**Pull request by wevonosky**
Adds a single TLE_URL to TLE_URLS list in tlefile.py

 - [x] Closes #52  
 - [x] Passes ``flake8 pyorbital``

### CODE REVIEW

**Comment by mraspaud** [comment]
Thanks for the fast reaction ! Would you mind adding you name to the author list on the top of the file ?

**Comment by wevonosky** [comment]
Done :)

**Comment by mraspaud** [comment]
Perfect!

**Comment by mraspaud** [comment]
@wevonosky thanks for the efficient work !

**Pull request merged**
