### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by meteoswiss-mdr**
Ciao Martin,

two changes to enable the parallax correction.
1st we reopened the near space calculation for geostationary satellites (sorry)
2nd a small function to identify a satellite in the norad file (get_norad_line)

Cheers, Ulrich

---

This change is [Reviewable](https://reviewable.io/reviews/pytroll/pyorbital/9)

### CODE REVIEW

**Comment by mraspaud** [comment]
@hau Could you check why the build is failing ?

**Comment by mraspaud** [comment]
@meteoswiss-mdr also, the get_norad_line could probably make use of the platforms.txt file...

**Comment by adybbroe** [comment]
@meteoswiss-mdr Could you check this old PR again, and resolve/answer to the questions/requests above?

**Comment by mraspaud** [comment]
@meteoswiss-mdr what is the status on this PR ?

**Pull request closed without merging**
